name: NbsDemo
main: de.petropia.nbsDemo.NbsDemo
author: Professor_Sam
version: 1.0.0
api-version: 1.18
depend: 
   - NoteBlockAPI
commands:
   Songs:
      description: Manage songs
      permission: nbsdemo.songs
permissions:
   nbsdemo.songs: 
      default: false
      description: allows a player to list and play songs